name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_names
      id: test_names
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test_names
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_NAMES_RESULTS: "${{steps.test_names.outputs.result}}"
      with:
        runners: test_names
